Update ubuntu_latest.yml
make tests fail more verbosely.

diff --git a/.github/workflows/ubuntu_latest.yml b/.github/workflows/ubuntu_latest.yml
--- a/.github/workflows/ubuntu_latest.yml
+++ b/.github/workflows/ubuntu_latest.yml
@@ -75,9 +75,9 @@ jobs:
           cat test.dist | clustDist > test.nwk
           ls test.*
           ./rarefan ../test/data/neisseria_small -q ../test/data/NMAA_0235.faa -r Nmen_2594.fas -o /tmp/rarefan_out | tee log
-          if [ $(grep -c "^15 RAYTs" log) -ne 1 ]; then exit 1; fi 
-          if [ $(grep -c "^184 21bp long sequences" log) -ne 1 ]; then exit 1; fi 
-          if [ $(grep -c "^48 REPINs" log) -ne 1 ]; then exit 1; fi 
+          if [ $(grep -c "^15 RAYTs" log) -ne 1 ]; then echo "Testing for 15 RAYTs failed."; exit 1;  fi 
+          if [ $(grep -c "^184 21bp long sequences" log) -ne 1 ]; then echo "Testing for 184 seeds failed."; exit 1; fi 
+          if [ $(grep -c "^48 REPINs" log) -ne 1 ]; then echo "Testing for 48 REPINs failed."; exit 1; fi 
 
           echo "====> Test passed <===="
           exit 0
